### ISSUE TITLE
Can't find System.Net.Http when building with VS 2017

### ISSUE THREAD

**Issue by tms-ninja** [karaluh/ScrobblerBrainz#10]
When I try to build from the master branch it fails as it can't find System.Net.Http. I think the relevant warning is:

> Severity	Code	Description	Project	File	Line	Suppression State
Warning		The primary reference "System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" or retarget your application to a framework version which contains "System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL".	ScrobblerBrainz			

I can build it if I install the Systen.Net.Http Nuget package but can't match the exact version and am cautious of it affecting dependencies.

Some people online say I need to add a reference to System.Net.Http but I don't have that. I wonder if I need to install the ASP.Net workload for VS, though as that's a massive download I thought it easier to ask.

**Comment by karaluh** [comment]
I added a reference, but installing by NuGet should be fine too.
