### ISSUE TITLE
Trouble saving token

### ISSUE THREAD

**Issue by loosenut** [karaluh/ScrobblerBrainz#12]
Is the token supposed to be displayed in the plugin settings after I click save?  Because it isn't, and ListenBrainz doesn't seem to be receiving any of my scrobbles.

Can you please help?

Thanks!

**Comment by karaluh** [comment]
Yes, the token should be displayed. What is the version number of the plugin you're using?

**Comment by loosenut** [comment]
I'm using the one I downloaded here:
https://github.com/karaluh/ScrobblerBrainz/releases/download/v1.1.0/mb_ScrobblerBrainz.dll
(which, btw, says v 1.0.0.0 when I look at it with Windows properties).

edit: I've tried this on two computers, one running MusicBee 3.5.8289, and one running 3.4.8033.  Thanks!

**Comment by karaluh** [comment]
Please try the more recent version of the plugin from here: https://github.com/karaluh/ScrobblerBrainz/releases/download/v1.1.1/mb_ScrobblerBrainz.dll

**Comment by loosenut** [comment]
Still not saving it.  I updated to the latest MusicBee (3.5.8289) and tried pasting the code in.  It was visible, then I hit apply, then save, then close.  When I reopen the Prefs/Plugins, it is blank.  I tried a few times.

**Comment by karaluh** [comment]
I'll look into it then.

**Comment by karaluh** [comment]
Unfortunately I'm unable to reproduce the issue. My guess is that the plugin is somehow not updated to the most recent version. Could you please download the version from the link below, update and post a screenshot of the plugin settings panel?

https://drive.google.com/file/d/1RPHkIkipQTkTMYUuLim3aB13uqUt0EXB/view?usp=sharing

**Comment by loosenut** [comment]
Happy to.  I started with a Plugins folder without any mb_ScrobblerBrainz.dll in it, then I added the one you linked to by copying it into C:\Program Files (x86)\MusicBee\Plugins .  Then I restarted MusicBee, and got the screenshot below.  To confirm: the problem is still happening.

![scrob](https://user-images.githubusercontent.com/2636321/191135055-e29269f3-8fdd-44b8-938e-9c3ceb5b76ad.jpg)

**Comment by karaluh** [comment]
It still looks like you're putting the file in the wrong place. Click the right mouse button on the MusicBee icon and choose **Open file location**, press the right mouse button on the icon again and choose **Properties**. Paste here everything what's in the **Target** field.

**Comment by loosenut** [comment]
"C:\Program Files (x86)\MusicBee\MusicBee.exe"

**Comment by loosenut** [comment]
I figured it out.  MusicBee saves the plugins in C:\Users\[username]\AppData\Roaming\MusicBee\Plugins when you install them with the "Add Plugin" feature.  So the old version of mb_ScrobblerBrainz.dll was there, and it was ignoring the updated .dll in C:\Program Files (x86)\MusicBee\Plugins .  I erased the one in AppData and now it saves the token.  Thank you for your help!

**Comment by karaluh** [comment]
You're welcome, happy scrobbling :)
