### ISSUE TITLE
Offline scrobbling

### ISSUE THREAD

**Issue by loosenut** [karaluh/ScrobblerBrainz#13]
Hi!  Thanks again for writing this.  From what I can tell, it doesn't scrobble unless it is connected to the internet.   Is it possible to queue scrobbles so they get scrobbled when I reconnect to the internet?  Consider that a feature request.  :)

Thanks, 
Jason

**Comment by karaluh** [comment]
You're welcome :) Offline scrobbling is implemented, I'll look into this.

**Comment by loosenut** [comment]
update: It looks like it eventually upload the play data.

**Comment by karaluh** [comment]
Great, thanks for the update.
