### ISSUE TITLE
Hi, I'm sorry, it just doesn't seem to be working at all.

### ISSUE THREAD

**Issue by HaganeNoYoshi** [karaluh/ScrobblerBrainz#16]
Followed all the instructions; installed, added token, and just nothing happens. I'm sure I'm making a very dumb mistake.

**Comment by karaluh** [comment]
Hi, sorry to hear that, let's try to find out why.
1. How MusicBee was installed?
2. How the plugin was installed?

**Comment by HaganeNoYoshi** [comment]
1.- .exe file from the website, version 3.5.8402 (this link, specifically https://www.dropbox.com/s/ivda4jg8oru81u4/MusicBee_Setup_3_5_8402.zip?dl=1)
2.- Downloaded, unzipped and placed into C:\Program Files (x86)\MusicBee\Plugins. I also tried with the 'add plugin' button, but neither would work.

**Comment by karaluh** [comment]
What plugin version is displayed in the settings window?

**Comment by HaganeNoYoshi** [comment]
2.0.0

**Comment by karaluh** [comment]
Everything looks fine, do you perhaps have ScrobblerBrainz folder located in C:\Program Files (x86)\MusicBee\Plugins? Is anything inside it?

**Comment by HaganeNoYoshi** [comment]
![imagen](https://user-images.githubusercontent.com/32465911/213879378-e4d022e3-1ec6-4758-96dd-07705f70e66b.png)
This is what C:\Program Files (x86)\MusicBee\Plugins looks like.
There's no Scrobblerbrainz folder; I just dropped the .dll files into Plugins.

**Comment by karaluh** [comment]
Everything seems to be working fine:
![image](https://user-images.githubusercontent.com/28653846/213911581-1630f117-3d58-42d2-832b-412081d9fb40.png)

What is it that you're trying to scrobble: regular files, some stream, etc.?

**Comment by HaganeNoYoshi** [comment]
Okay that's pretty weird.
I don't recognize that track like, at all.
And I was asleep at the moment those listens were registered.

I'm trying to scrobble regular files stored locally.

**Comment by karaluh** [comment]
I know, I scrobbled those on your behalf while investigating the problem :)

Do you perhaps also have Last.fm scrobbler enabled?

**Comment by HaganeNoYoshi** [comment]
Ohh, okok, lolol, got it.

![imagen](https://user-images.githubusercontent.com/32465911/213953194-4971882b-0b35-482c-862e-ee1faaf057b6.png)

No, it's disabled and it's always been.

**Comment by karaluh** [comment]
I'm almost out of ideas what might be wrong. One last thing you might check is if the track play count gets increased after you finish listening to a song.

**Comment by HaganeNoYoshi** [comment]
Okay, my listens have been updated, however, they don't come from scrobblebrainz, but from another scrobbler app that works with Plex.

It doesn't seem like my listens on musicbee are affecting the amount of listens.
That's ok if you can't find a solution to this; fairly sure the error may be on my end. Like my router configuration or something silly like that. :'p

**Comment by karaluh** [comment]
If it's ok to you, it's also ok to me :) But if you want to get this fixed, check if the play count in MusicBee increases for a track that you've just listened because that's the trigger in the plugin to scrobble to ListenBrainz.

On an unrelated note, you might want to reset your ListenBrainz token because it's public now and anyone can mess your listen history. I removed the screenshot that "leaked" it but it probably got cached on Google etc.

**Comment by HaganeNoYoshi** [comment]
Hi! Yes, the play count gets updated on MusicBee, but no changes on ListenBrainz, sadly.

**Comment by karaluh** [comment]
OK then, I'll prepare for you a build with debug logging, stay tuned.

**Comment by karaluh** [comment]
While I was preparing the debug build for you I noticed that the directory, where the error log should be stored is not being created. It might be that there are errors while submitting your scrobbles but they aren't being logged. Investigating.

**Comment by karaluh** [comment]
[sb_debug.zip](https://github.com/karaluh/ScrobblerBrainz/files/10679109/sb_debug.zip)

This is a build with debug logging enabled. Extract the archive to your MBee plugins directory and start the program. Note the path that's displayed when the program starts, play a few tracks and attach here debug.log and error log if it exists. Both files will be in the directory that was displayed when the program started.

**Comment by HaganeNoYoshi** [comment]
Understood. I'll do this and report back with the .log files. Thank you so much for being so willing to help!

**Comment by HaganeNoYoshi** [comment]
Ok, idk what just happened, but *now* it works.
I stg, I followed the exacvt same installation process, did absolutely nothing different.
Yet, now it's working, while before it didn't.

**Comment by karaluh** [comment]
That's great, happy scrobbling :)
