### ISSUE TITLE
Scrobbles are being submitted with listen times at the end of the track rather than the start

### ISSUE THREAD

**Issue by luh-azer** [karaluh/ScrobblerBrainz#18]
The new "finishes at" feature for manual listen submits shows that the "listened_at" time of a scrobble is the time of the start of the track. Scrobbles submitted with ScrobblerBrainz instead have the "listened_at" time at the end of the listen. For instance, a 4 minute track that started at 12:00 PM appears as a listen from 12:04 PM.

**Comment by ghost** [comment]
Are listens on ListenBrainz generally intended to be submitted from the start of the track, rather than the end?

**Comment by luh-azer** [comment]
According to the [API documentation](https://listenbrainz.readthedocs.io/en/latest/users/api/core.html), "Listens should be submitted for tracks when the user has listened to half the track or 4 minutes of the track, whichever is lower. If the user hasn’t listened to 4 minutes or half the track, it doesn’t fully count as a listen and should not be submitted." 

Though my issue wasn't the submission times, but the listen times not reflecting the start time of the track.

**Comment by ghost** [comment]
Yeah, that's what I was going for, wrong wording lol. I'll have a crack at it when I'm able to - currently not able to access a Windows machine right now.

**Comment by karaluh** [comment]
PR merged, listen times seem to be correct now. Thank you all for contributing <3
