### ISSUE TITLE
Only scrobble tracks after they have been played for some time.

### ISSUE THREAD

**Issue by Gremious** [karaluh/ScrobblerBrainz#5]
Currently, tracks get scrobbled the moment you play them, meaning if I start an album and just skip 5 tracks ahead by pressing the "next track" button 5 times, I will have scrobbled 5 tracks that I didn't actually listen to, e.g.:

![image](https://user-images.githubusercontent.com/21365711/83349686-b8a70c80-a32e-11ea-87f4-1bf0875e6a91.png)

Please instead consider only scrobbling after 15 seconds of playtime have passed (unless the track is less than 15 seconds), or perhaps after it was actively played for at least half it's lenght (which sounds nicer and more consistent to me).

**Comment by karaluh** [comment]
Interesting, they should be scrobbled only when MusicBee increases the playcount. I'll look into this, thanks for the report.
