### ISSUE TITLE
Feature Request: Match preferences text field to musicbee skin

### ISSUE THREAD

**Issue by jtpavlock** [karaluh/ScrobblerBrainz#6]
This is a minor feature request/nitpick, but something I immediately noticed is the text field to enter your listenbrainz user token looked out of place.

Currently 
![image](https://user-images.githubusercontent.com/26807251/83983752-9d239f00-a8f6-11ea-93cb-3d58dd0a6efe.png)

Normal text fields
![image](https://user-images.githubusercontent.com/26807251/83983767-b4628c80-a8f6-11ea-836f-d227f4cd3856.png)

Just something to consider.

**Comment by karaluh** [comment]
Thanks for the report, this annoys me too :) Will look into this.
