### ISSUE TITLE
Support submitting "playing now"

### ISSUE THREAD

**Issue by phw** [karaluh/ScrobblerBrainz#8]
It would be great if the plugin would also support submitting the "playing now" notification.

From the LB side this looks exactly like a single listen submission, but with `listen_type` of `"playing_now"` and no timestamp. See

https://listenbrainz.readthedocs.io/en/production/dev/json/#json-doc

**Comment by karaluh** [comment]
Yes, that shouldn't be too hard, putting on the TODO list. Thanks for the report!

**Comment by ghost** [comment]
I've implemented this on a fork. I'm happy to submit a PR if all's good. https://github.com/Viktini/ScrobblerBrainz/commit/9a0d560714e62a188b1ba22aef8af40ab844cd9d

**Comment by karaluh** [comment]
Thanks! I'll try to look at it next week.

**Comment by forenta** [comment]
Would be nice if the next week would come one day.

Thanks anyway for your work :)

**Comment by ghost** [comment]
@forenta: I've since moved to Quod Libet (used to run MusicBee in WINE), but I can help get this and the code for MBID tag grabbing merged if Karaluh wants it. Also get the JSON output updated to ListenBrainz's current spec :)

**Comment by karaluh** [comment]
Yeah, life got in the way :/ But if you submit the PR i promise to review it and release a new version.

**Comment by ghost** [comment]
Same here with life. I'll make sure the JSON is updated (might as well update that while doing this) and I'll send a pull request with everything included (I also implemented #7 with TagLib#, which also got a new version bump, but I'll work on working with that later. I want to push the current working code I have now.)

**Comment by Viktini** [comment]
Ah, before I do, are you okay with moving the solution up to .NET 4.8?  MusicBee 3.5 and I believe TagLib# will require 4.8 from here on out, so I thought I'd ask.

**Comment by karaluh** [comment]
Great, thank you a lot for this! I plan to merge and release it this weekend.
