### ISSUE TITLE
It is not working in latest version of Musicbee 

### ISSUE THREAD

**Issue by weeshinwang** [karaluh/ScrobblerBrainz#9]
I have latest version of Musicbee from Microsoft Store (3.4.7764 Store), after I install this plugin, I have no space to put in ListenBrainz token. 
Screenshot attached.

![image](https://user-images.githubusercontent.com/14191453/118422068-0e69f580-b6f5-11eb-9166-1f65fc371708.png)

**Comment by weeshinwang** [comment]
My guess is that the height setting of input box is wrong, the UI doesn't show every settings of the plugin.

**Comment by karaluh** [comment]
I just tried to reproduce, but for me the most recent version from the MS Store is 3.4.7805. Can you verify?

Sorry for the delayed response.

**Comment by weeshinwang** [comment]
Thanks so much for the response. I have just updated to 3.4.7805 but the problem still exists.
This time I try to paste my token into the little bit gap in the setting menu, it works!😂😂
But I think it might still be a problem cause I just assume it is not a normal height for a input box.
![image](https://user-images.githubusercontent.com/14191453/119233257-c286d880-bb5a-11eb-9a75-a4377a8efe50.png)

**Comment by weeshinwang** [comment]
after hours of scrobbling it stops working suddenly without any indications
update:
I have re-installed the plugin, it works again, very strange🤔🤔

**Comment by karaluh** [comment]
Could you please paste the full screenshot of the settings window?

**Comment by weeshinwang** [comment]
![image](https://user-images.githubusercontent.com/14191453/119288384-05d86880-bc7b-11eb-8339-4a8684715afc.png)

**Comment by weeshinwang** [comment]
I figure out the problem might relates to screen resolution settings.
After I changed the resolution from 2560 x 1440 to 1920 x 1080, I can see the outline of the input box, but it is not normal though.

![image](https://user-images.githubusercontent.com/14191453/119288930-2f45c400-bc7c-11eb-9a06-26986be94d32.png)

**Comment by karaluh** [comment]
Thanks for the report, I'll look into this
